[package]
name = "gram-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Gram notation serialization/deserialization"

[dependencies]

[dev-dependencies]
proptest = { workspace = true }
insta = { workspace = true }

[lib]
name = "gram_codec"
path = "src/lib.rs"

